### ISSUE TITLE
Hello bro need a help

### ISSUE THREAD

**Issue by samarths2003** [Priyansh42/Spendee-Expense-Tracker-and-Budget-Manager#1]
For firebase how can i access

**Comment by samarths2003** [comment]
Please bro day after tomorrow i have to submit 😭

**Comment by Priyansh42** [comment]
Thank you for viewing our project and considering it worthy for your project. But as you are an outsider, we can't give direct access to anyone outside our project group. I hope you understand, this is for the security purpose.

Also, I haven't tried connecting to another Firebase database yet if any Firebase database is already connected to the Android project. But below are some links that might help you.
https://youtu.be/SRpdgIl8j-g
https://youtu.be/Thysuf7kq28

IMPORTANT NOTE:
When integrating your own Firebase, please ensure that it does not affect the original project or its Firebase database. You can follow the above resources carefully to integrate your Firebase without any conflicts.

**Comment by Priyansh42** [comment]
For any other queries, you can always contact me.

**Comment by samarths2003** [comment]
Brother i have successfully connected to my firebase database
yesterday,thank you for you helping 🙂

**Comment by Priyansh42** [comment]
I am happy to hear from you that you have successfully connected to your Firebase database. I hope the resources that I provided to you helped you well.

For any other queries, you can always contact me.
